
logging:
  level:
    root: INFO
    org.springframework: INFO
    pe.realplaza.workflow: INFO
    pe.realplaza.workflow.repository: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.simple.SimpleJdbcCall: INFO
    org.springframework.web.client.RestTemplate: INFO

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"

server:
  port: 8080
  servlet:
    context-path: /workflow


spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/workflow?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler.instanceName: ms-rp-workflow
      org.quartz.scheduler.instanceId: AUTO
  jackson:
    time-zone: America/Lima
    date-format: yyyy-MM-dd HH:mm:ss
    locale: es_PE
    default-property-inclusion: non_null

mybatis:
mapper-locations: classpath:/mapper/*.xml

app:
  name: Workflow

api:
  url: https://api.realplazalabs.com/v1/storage/uploadFile
  x-api-key: algo
  util-send-email: https://api.devrealplazaonline.com/v1/dev/common/emails
  token-util-send-email:  0I488blpaB1zfu43CYne1qbfv4k5bo11EugDhzj6

identity-provider:
  url-introspect: https://api.realplazalabs.com/v1/identity/introspect
  resource-id: ms-rp-workflowmanager
  resource-secret: 80816C18-C8A9-4D6D-A296-2CC01F602427

disable-security: true